export const MapStateEnum = {
    PINGING: "PINGING",
    CREATING_TASK: "CREATING_TASK",
    PULLING_NODE_LIST: "PULLING_NODE_LIST",
    DISTRIBUTE_TASKS: "DISTRIBUTE_TASKS",
    GETTING_RESPONSE: "GETTING_RESPONSE",
    SUCCESS: "SUCCESS"
}